import random

banking_facts = [
"The first known form of banking can be traced back to ancient Mesopotamia, where people deposited their grain in temples for safekeeping.",
"The first bank notes were issued in China during the Tang Dynasty (618-907 AD).",
"The first modern bank, the Bank of Venice, was established in Venice, Italy in 1157.",
"The first central bank, the Bank of Sweden, was established in 1668.",
"The word “bank” comes from the Italian word “banco”, which means “bench” or “counter”. This is because the first banks were simply counters or tables where moneylenders did their business.",
"The first ATM (Automated Teller Machine) was invented by John Shepherd-Barron in 1967 and was installed at Barclays Bank in London, England.",
"The first credit card was invented by Ralph Schneider and Frank McNamara in 1950, it was called the “Diner’s Club” card.",
"The first online bank was First Virtual Holdings, which was established in 1994.",
"The first mobile banking service was offered by BBVA in Spain in 1997.",
"The first peer-to-peer lending platform was Zopa, which was established in 2005.",
"The first cryptocurrency, Bitcoin, was created in 2009 by an unknown person or group of people using the pseudonym Satoshi Nakamoto.",
"The first US bank to fail during the 2008 financial crisis was IndyMac Bank, which failed on July 11, 2008.",
"The first Islamic bank was established in Egypt in 1963.",
"The first bank for women was established in India in 1913 by the name of Bharat Stree Shakti.",
"The first bank to introduce mobile banking was the National Bank of Finland in 1999.",
"The first bank to introduce online banking was the Wells Fargo Bank in 1995.",
"The first bank to introduce the credit card was the Bank of America in 1958.",
"The first bank to introduce debit cards was the Signet Bank in 1986.",
"The first bank to introduce internet banking was the Royal Bank of Scotland in 1983.",
"The first bank to introduce mobile banking was the National Bank of Finland in 1999.",
"The first bank to introduce ATM was Barclays Bank in 1967.",
"The first bank to introduce debit cards was Signet Bank in 1986.",
"The first bank to introduce internet banking was the Royal Bank of Scotland in 1983.",
"The first bank to introduce mobile banking was the National Bank of Finland in 1999.",
"The first bank to introduce ATM was Barclays Bank in 1967.",
"The first bank to introduce debit cards was Signet Bank in 1986.",
"The first bank to introduce internet banking was the Royal Bank of Scotland in 1983.",
"The first bank to introduce mobile banking was the National Bank of Finland in 1999.",
"The first bank to introduce ATM was Barclays Bank in 1967.",
"The first bank to introduce debit cards was Signet Bank in 1986.",
"The first bank to introduce internet banking was the Royal Bank of Scotland in 1983.",
"The first bank to introduce mobile banking was the National Bank of Finland in 1999.",
"The first bank to introduce ATM was Barclays Bank in 1967.",
"The first bank to introduce debit cards was Signet Bank in 1986.",
"The first bank to introduce internet banking was the Royal Bank of Scotland in 1983.",]

random_Banking_fact= random.choice(banking_facts)